name: cordex-examples
dependencies:
  - cmor>=3.7.0
  - cartopy>=0.20
  - matplotlib-base
  - numpy
  - pooch
  - regionmask
  - setuptools
  - xarray
  - cf_xarray
  - cftime
  - netCDF4
  - xesmf
  - cfchecker
  - compliance-checker
  - cdo
  - python-cdo
  - jupyter-book
  - intake-esm
  - ghp-import
  - fsspec
  - requests
  - aiohttp
  - pip:
    - git+https://github.com/euro-cordex/py-cordex.git # always use master for now
