name: cmor-examples
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cmor>=3.8.0
  - cartopy
  - matplotlib-base
  - numpy
  - xarray
  - netCDF4
  - cfchecker
  - compliance-checker
  - cdo
  - python-cdo
  - pint
  - py-cordex
  - pip:
    - cc-plugin-wcrp
  #  - git+https://github.com/euro-cordex/py-cordex.git # always use master for now
