name: cordex-examples
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cmor
  - cartopy
  - matplotlib-base
  - numpy
  - pooch
  - xarray
  - cftime
  - netCDF4
  - cdo
  - python-cdo
  - requests
  - aiohttp
  - pip:
    - git+https://github.com/euro-cordex/py-cordex.git # always use master for now
