name: cmor-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  - xarray
  - numpy<1.24 # fixed until next cmor release
  - netCDF4
  - pytest
  - py-cordex
  - cf_xarray
  - cmor>=3.7.0
  - fsspec
  - requests
  - aiohttp
  - cfchecker
  - cdo
  - python-cdo
  - pint
  - pip:
    - git+https://github.com/euro-cordex/py-cordex.git # always use master for now
