name: cmor-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  - xarray
  - netCDF4
  - pytest
  - py-cordex
  - cf_xarray
  - cmor
  - fsspec
  - requests
  - aiohttp
  - cfchecker
  - cdo
  - python-cdo
  - pip:
    - git+https://github.com/euro-cordex/py-cordex.git # always use master for now
