name: cmor-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  - xarray
  - netCDF4
# for testing
  - pytest
  - py-cordex
  - cf_xarray
  - pip:
    - git+https://github.com/remo-rcm/pyremo.git # always use master for now
