name: cmor-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  - xarray
  - netCDF4
# for testing
  - pytest
  - py-cordex
  - cf_xarray
  - cmor
  - fsspec
  - requests
  - aiohttp
  - cfchecker
  - pyremo
