name: update controlled vocabulary

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
  schedule:
  - cron: "0 0 * * *"


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  update_controlled_vocabulary:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Update controlled vocabulary
      #env:
      # WANDB_CONSOLE: "off"
      run: |
        python scripts/createCORDEXCV.py
        mv CORDEX_CV.json  Tables
  #  - name: pushes results to table repository
  #    env:
       # API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
  #    run: bash update-tables.sh
