name: update controlled vocabulary

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    paths:
      - 'CORDEX_*.json'
    branches:
      - main


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  update_controlled_vocabulary:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pre-commit
        #pre-commit install
    - name: Update controlled vocabulary
      #env:
      # WANDB_CONSOLE: "off"
      run: |
        python scripts/createCORDEXCV.py
        mv CORDEX_CV.json  Tables
    - name: Commit CORDEX_CV.json
      run: |
        git config --global user.name "github-actions[bot]"
        (pre-commit run --all-files) || true
        git pull origin main
        #git config --global user.email 'your-username@users.noreply.github.com'
        git commit Tables/CORDEX_CV.json -m "automated CV update"
        git push
